name = "Expanded Storage"
filename = "expandedstorage-7.4.0-beta.2+1.18.2-quilt.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/psjeHi3j/versions/7.4.0-beta.2+quilt/expandedstorage-7.4.0-beta.2%2B1.18.2-quilt.jar"
hash-format = "sha1"
hash = "bd673a46b8450fb831cb76898c43332d18c7c362"

[update]
[update.modrinth]
mod-id = "psjeHi3j"
version = "5yzSAAMz"
