name = "Modern Industrialization"
filename = "Modern-Industrialization-1.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Gov5Dboq/versions/1.1.1/Modern-Industrialization-1.1.1.jar"
hash-format = "sha1"
hash = "dc6630422dc8566dc99c9fbaa0d564eef2e9822d"

[update]
[update.modrinth]
mod-id = "Gov5Dboq"
version = "rPiUix8v"
