name = "qCraft Reimagined"
filename = "qcraft-1.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/uwzLLQUA/versions/1.1.0/qcraft-1.1.0.jar"
hash-format = "sha1"
hash = "d0621f82ea5b93776a7ba039d50ef547236c9344"

[update]
[update.modrinth]
mod-id = "uwzLLQUA"
version = "lsPUi68v"
