name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.2-2.2.44.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.44/voicechat-fabric-1.18.2-2.2.44.jar"
hash-format = "sha1"
hash = "c8e16c4ed6ea4572fd4ecbbed04af9c5a3d7fd2e"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "UWBnMOdJ"
