name = "TaterCart"
filename = "tatercart-1.0.0-pre.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GFWR9kLQ/versions/1.0.0-pre.3/tatercart-1.0.0-pre.3.jar"
hash-format = "sha1"
hash = "47fb6b3993d912b5e75c1971fba98292672b00a2"

[update]
[update.modrinth]
mod-id = "GFWR9kLQ"
version = "HseHRwD7"
